{
  "swagger": "2.0",
  "info": {
    "title": "\u30ED\u30FC\u30F3\u30DE\u30A4\u30AF\u30ED\u30B5\u30FC\u30D3\u30B9",
    "version": "1"
  },
  "paths": {
    "/\u652F\u5E97\u8A73\u7D30": {
      "get": {
        "responses": {
          "200": {
            "description": "\u30D6\u30E9\u30F3\u30C1\u306E\u8A73\u7D30\u3092\u53D6\u5F97\u3057\u307E\u3057\u305F",
            "schema": {
              "$ref": "#/definitions/\u30D6\u30E9\u30F3\u30C1"
            }
          }
        }
      }
    },
    "/\u30ED\u30FC\u30F3\u7533\u3057\u8FBC\u307F": {
      "post": {
        "parameters": [
          {
            "in": "body",
            "name": "\u30ED\u30FC\u30F3\u7533\u3057\u8FBC\u307F",
            "schema": {
              "$ref": "#/definitions/\u30ED\u30FC\u30F3\u7533\u3057\u8FBC\u307F"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "\u8AAC\u660E",
            "schema": {
              "$ref": "#/definitions/\u5FDC\u7528"
            }
          }
        }
      }
    },
    "/\u8ECA\u4E21\u8A73\u7D30": {
      "get": {
        "responses": {
          "200": {
            "description": "\u8ECA\u4E21\u306E\u8A73\u7D30\u3092\u6B63\u5E38\u306B\u53D6\u5F97\u3057\u307E\u3057\u305F",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/\u8ECA\u4E21\u8A73\u7D30"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "\u8ECA\u4E21": {
      "type": "object",
      "properties": {
        "\u7D04\u30DE\u30A4\u30EB": {
          "type": "string"
        },
        "\u30B7\u30C6\u30A3": {
          "type": "string"
        },
        "\u63A8\u5B9A\u5024": {
          "type": "integer",
          "format": "int32"
        },
        "\u767B\u9332\u5DDE": {
          "type": "string"
        },
        "\u58F2\u308A\u624B\u4F4F\u6240": {
          "type": "string"
        },
        "\u58F2\u308A\u624B\u540D": {
          "type": "string"
        },
        "\u72B6\u614B": {
          "type": "string"
        },
        "\u901A\u308A\u72B6\u614B": {
          "type": "string"
        },
        "transactionType": {
          "type": "string"
        },
        "\u30D3\u30FC\u30C7\u30F3": {
          "type": "string"
        },
        "\u8ECA\u4E21Id": {
          "type": "integer",
          "format": "int32"
        },
        "\u8ECA\u4E21Make": {
          "type": "string"
        },
        "\u8ECA\u4E21Model": {
          "type": "string"
        },
        "\u8ECA\u4E21Type": {
          "type": "string"
        },
        "\u8ECA\u4E21Year": {
          "type": "integer",
          "format": "int32"
        },
        "zipCode": {
          "type": "string"
        }
      },
      "example": {
        "zipCode": "zipCode",
        "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
        "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
        "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
        "\u8ECA\u4E21Make": "\u8ECA\u4E21Make",
        "transactionType": "transactionType",
        "\u63A8\u5B9A\u5024": 7,
        "\u8ECA\u4E21Year": 1,
        "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
        "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
        "\u8ECA\u4E21Model": "\u8ECA\u4E21Model",
        "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
        "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
        "\u72B6\u614B": "\u72B6\u614B",
        "\u8ECA\u4E21Id": 1,
        "\u8ECA\u4E21Type": "\u8ECA\u4E21Type"
      }
    },
    "\u8ECA\u4E21\u8A73\u7D30": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "\u30D3\u30FC\u30C7\u30F3": {
          "type": "string"
        },
        "\u8ECA\u4E21\u8A73\u7D30sId": {
          "type": "integer",
          "format": "int32"
        },
        "\u8ECA\u4E21Make": {
          "type": "string"
        },
        "\u8ECA\u4E21Model": {
          "type": "string"
        },
        "\u8ECA\u4E21Type": {
          "type": "string"
        },
        "\u8ECA\u4E21Year": {
          "type": "integer",
          "format": "int32"
        }
      },
      "example": {
        "\u8ECA\u4E21Year": 6,
        "\u8ECA\u4E21\u8A73\u7D30sId": 0,
        "\u8ECA\u4E21Model": "\u8ECA\u4E21Model",
        "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
        "id": "id",
        "\u8ECA\u4E21Make": "\u8ECA\u4E21Make",
        "\u8ECA\u4E21Type": "\u8ECA\u4E21Type"
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "addTypePrevious": {
          "type": "string"
        },
        "addTypePrimary": {
          "type": "string"
        },
        "annualIncome": {
          "type": "integer"
        },
        "anyPoliticalRelationship": {
          "type": "boolean"
        },
        "apartmentNo": {
          "type": "string"
        },
        "citizenOf": {
          "type": "boolean"
        },
        "\u30B7\u30C6\u30A3": {
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "housingStatus": {
          "type": "string"
        },
        "initial": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "monthlyPayment": {
          "type": "integer"
        },
        "monthsAtCurrAdd": {
          "type": "integer",
          "format": "int32"
        },
        "otherIncome": {
          "type": "string"
        },
        "permanentResidence": {
          "type": "boolean"
        },
        "phoneNo": {
          "type": "integer",
          "format": "int32"
        },
        "ssn": {
          "type": "integer",
          "format": "int32"
        },
        "\u72B6\u614B": {
          "type": "string"
        },
        "\u901A\u308A\u72B6\u614B": {
          "type": "string"
        },
        "suffix": {
          "type": "string"
        },
        "uid": {
          "type": "integer",
          "format": "int32"
        },
        "userName": {
          "type": "string"
        },
        "yearsAtCurrAdd": {
          "type": "integer",
          "format": "int32"
        },
        "zipCode": {
          "type": "string"
        }
      },
      "example": {
        "apartmentNo": "apartmentNo",
        "lastName": "lastName",
        "zipCode": "zipCode",
        "annualIncome": 5,
        "housingStatus": "housingStatus",
        "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
        "permanentResidence": true,
        "suffix": "suffix",
        "phoneNo": 1234,
        "ssn": 3,
        "uid": 2,
        "yearsAtCurrAdd": 4,
        "monthlyPayment": 2,
        "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
        "\u72B6\u614B": "\u72B6\u614B",
        "addTypePrimary": "addTypePrimary",
        "email": "email",
        "initial": "initial",
        "citizenOf": true,
        "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
        "userName": "userName",
        "otherIncome": "otherIncome",
        "firstName": "firstName",
        "addTypePrevious": "addTypePrevious",
        "anyPoliticalRelationship": true,
        "monthsAtCurrAdd": 7
      }
    },
    "\u30D6\u30E9\u30F3\u30C1": {
      "type": "object",
      "properties": {
        "apartmentNo": {
          "type": "string"
        },
        "\u30D6\u30E9\u30F3\u30C1Id": {
          "type": "integer",
          "format": "int32"
        },
        "\u30D6\u30E9\u30F3\u30C1Name": {
          "type": "string"
        },
        "\u30B7\u30C6\u30A3": {
          "type": "string"
        },
        "contactPerson": {
          "type": "string"
        },
        "phoneNo": {
          "type": "string"
        },
        "\u72B6\u614B": {
          "type": "string"
        },
        "\u901A\u308A\u72B6\u614B": {
          "type": "string"
        },
        "zipCode": {
          "type": "string"
        }
      },
      "example": {
        "apartmentNo": "apartmentNo",
        "\u30D6\u30E9\u30F3\u30C1Id": 0,
        "zipCode": "zipCode",
        "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
        "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
        "\u30D6\u30E9\u30F3\u30C1Name": "\u30D6\u30E9\u30F3\u30C1Name",
        "contactPerson": "contactPerson",
        "\u72B6\u614B": "\u72B6\u614B",
        "phoneNo": "phoneNo"
      }
    },
    "\u5FDC\u7528": {
      "type": "object",
      "properties": {
        "\u5FDC\u7528Id": {
          "type": "string"
        },
        "\u5FDC\u7528\u72B6\u614B": {
          "type": "string"
        },
        "\u5FDC\u7528Status": {
          "type": "string"
        },
        "\u30D6\u30E9\u30F3\u30C1": {
          "$ref": "#/definitions/\u30D6\u30E9\u30F3\u30C1"
        },
        "loanTerm": {
          "type": "integer",
          "format": "int32"
        },
        "loanYearPeriod": {
          "type": "integer",
          "format": "int32"
        },
        "ownerShip": {
          "type": "string"
        },
        "pendingWith": {
          "type": "string"
        },
        "requestedAmt": {
          "type": "integer",
          "format": "int32"
        },
        "uid": {
          "type": "integer",
          "format": "int32"
        },
        "user": {
          "$ref": "#/definitions/User"
        },
        "userName": {
          "type": "string"
        },
        "\u8ECA\u4E21": {
          "$ref": "#/definitions/\u8ECA\u4E21"
        }
      },
      "example": {
        "pendingWith": "pendingWith",
        "requestedAmt": 1,
        "\u5FDC\u7528\u72B6\u614B": "\u5FDC\u7528\u72B6\u614B",
        "ownerShip": "ownerShip",
        "userName": "userName",
        "\u30D6\u30E9\u30F3\u30C1": {
          "apartmentNo": "apartmentNo",
          "\u30D6\u30E9\u30F3\u30C1Id": 0,
          "zipCode": "zipCode",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "\u30D6\u30E9\u30F3\u30C1Name": "\u30D6\u30E9\u30F3\u30C1Name",
          "contactPerson": "contactPerson",
          "\u72B6\u614B": "\u72B6\u614B",
          "phoneNo": "phoneNo"
        },
        "\u8ECA\u4E21": {
          "zipCode": "zipCode",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
          "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
          "\u8ECA\u4E21Make": "\u8ECA\u4E21Make",
          "transactionType": "transactionType",
          "\u63A8\u5B9A\u5024": 7,
          "\u8ECA\u4E21Year": 1,
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
          "\u8ECA\u4E21Model": "\u8ECA\u4E21Model",
          "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
          "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
          "\u72B6\u614B": "\u72B6\u614B",
          "\u8ECA\u4E21Id": 1,
          "\u8ECA\u4E21Type": "\u8ECA\u4E21Type"
        },
        "loanYearPeriod": 6,
        "uid": 5,
        "loanTerm": 0,
        "\u5FDC\u7528Status": "\u5FDC\u7528Status",
        "\u5FDC\u7528Id": "\u5FDC\u7528Id",
        "user": {
          "apartmentNo": "apartmentNo",
          "lastName": "lastName",
          "zipCode": "zipCode",
          "annualIncome": 5,
          "housingStatus": "housingStatus",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "permanentResidence": true,
          "suffix": "suffix",
          "phoneNo": 9,
          "ssn": 3,
          "uid": 2,
          "yearsAtCurrAdd": 4,
          "monthlyPayment": 2,
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "\u72B6\u614B": "\u72B6\u614B",
          "addTypePrimary": "addTypePrimary",
          "email": "email",
          "initial": "initial",
          "citizenOf": true,
          "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
          "userName": "userName",
          "otherIncome": "otherIncome",
          "firstName": "firstName",
          "addTypePrevious": "addTypePrevious",
          "anyPoliticalRelationship": true,
          "monthsAtCurrAdd": 7
        }
      }
    },
    "\u30ED\u30FC\u30F3\u7533\u3057\u8FBC\u307F": {
      "type": "object",
      "properties": {
        "\u5FDC\u7528": {
          "$ref": "#/definitions/\u5FDC\u7528"
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      },
      "example": {
        "\u5FDC\u7528": {
          "pendingWith": "pendingWith",
          "requestedAmt": 1,
          "\u5FDC\u7528\u72B6\u614B": "\u5FDC\u7528\u72B6\u614B",
          "ownerShip": "ownerShip",
          "userName": "userName",
          "\u30D6\u30E9\u30F3\u30C1": {
            "apartmentNo": "apartmentNo",
            "\u30D6\u30E9\u30F3\u30C1Id": 0,
            "zipCode": "zipCode",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "\u30D6\u30E9\u30F3\u30C1Name": "\u30D6\u30E9\u30F3\u30C1Name",
            "contactPerson": "contactPerson",
            "\u72B6\u614B": "\u72B6\u614B",
            "phoneNo": "phoneNo"
          },
          "\u8ECA\u4E21": {
            "zipCode": "zipCode",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
            "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
            "\u8ECA\u4E21Make": "\u8ECA\u4E21Make",
            "transactionType": "transactionType",
            "\u63A8\u5B9A\u5024": 7,
            "\u8ECA\u4E21Year": 1,
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
            "\u8ECA\u4E21Model": "\u8ECA\u4E21Model",
            "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
            "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
            "\u72B6\u614B": "\u72B6\u614B",
            "\u8ECA\u4E21Id": 1,
            "\u8ECA\u4E21Type": "\u8ECA\u4E21Type"
          },
          "loanYearPeriod": 6,
          "uid": 5,
          "loanTerm": 0,
          "\u5FDC\u7528Status": "\u5FDC\u7528Status",
          "\u5FDC\u7528Id": "\u5FDC\u7528Id",
          "user": {
            "apartmentNo": "apartmentNo",
            "lastName": "lastName",
            "zipCode": "zipCode",
            "annualIncome": 5,
            "housingStatus": "housingStatus",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "permanentResidence": true,
            "suffix": "suffix",
            "phoneNo": 9,
            "ssn": 3,
            "uid": 2,
            "yearsAtCurrAdd": 4,
            "monthlyPayment": 2,
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "\u72B6\u614B": "\u72B6\u614B",
            "addTypePrimary": "addTypePrimary",
            "email": "email",
            "initial": "initial",
            "citizenOf": true,
            "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
            "userName": "userName",
            "otherIncome": "otherIncome",
            "firstName": "firstName",
            "addTypePrevious": "addTypePrevious",
            "anyPoliticalRelationship": true,
            "monthsAtCurrAdd": 7
          }
        }
      }
    }
  }
}
