{
  "openapi": "3.0.0",
  "info": {
    "title": "\u30ED\u30FC\u30F3\u30DE\u30A4\u30AF\u30ED\u30B5\u30FC\u30D3\u30B9",
    "version": "1"
  },
  "paths": {
    "/\u652F\u5E97Details": {
      "get": {
        "responses": {
          "200": {
            "description": "Branch\u306EDetails\u3092\u53D6\u5F97\u3057\u307E\u3057\u305F",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Branch"
                }
              }
            }
          }
        }
      }
    },
    "/\u30D3\u30B9\u306B\u4FDD\u5B58\u3057\u307E\u3059": {
      "post": {
        "responses": {
          "200": {
            "description": "\u8AAC\u660E",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Application"
                }
              }
            }
          }
        }
      }
    },
    "/\u5E38\u306B\u53D6\u5F97\u3057\u307E\u3057\u305F": {
      "get": {
        "responses": {
          "200": {
            "description": "Vehicle\u306EDetails\u3092\u6B63\u5E38\u306B\u53D6\u5F97\u3057\u307E\u3057\u305F",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/VehicleDetails"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Vehicle": {
        "type": "object",
        "properties": {
          "\u7D04\u30DE\u30A4\u30EB": {
            "type": "string"
          },
          "\u30B7\u30C6\u30A3": {
            "type": "string"
          },
          "\u63A8\u5B9A\u5024": {
            "type": "integer",
            "format": "int32"
          },
          "\u767B\u9332\u5DDE": {
            "type": "string"
          },
          "\u58F2\u308A\u624B\u4F4F\u6240": {
            "type": "string"
          },
          "\u58F2\u308A\u624B\u540D": {
            "type": "string"
          },
          "\u72B6\u614B": {
            "type": "string"
          },
          "\u901A\u308A\u72B6\u614B": {
            "type": "string"
          },
          "transactionType": {
            "type": "string"
          },
          "\u30D3\u30FC\u30C7\u30F3": {
            "type": "string"
          },
          "VehicleId": {
            "type": "integer",
            "format": "int32"
          },
          "VehicleMake": {
            "type": "string"
          },
          "VehicleModel": {
            "type": "string"
          },
          "VehicleType": {
            "type": "string"
          },
          "VehicleYear": {
            "type": "integer",
            "format": "int32"
          },
          "zipCode": {
            "type": "string"
          }
        },
        "example": {
          "zipCode": "zipCode",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
          "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
          "VehicleMake": "VehicleMake",
          "transactionType": "transactionType",
          "\u63A8\u5B9A\u5024": 7,
          "VehicleYear": 1,
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
          "VehicleModel": "VehicleModel",
          "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
          "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
          "\u72B6\u614B": "\u72B6\u614B",
          "VehicleId": 1,
          "VehicleType": "VehicleType"
        }
      },
      "VehicleDetails": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "\u30D3\u30FC\u30C7\u30F3": {
            "type": "string"
          },
          "VehicleDetailsId": {
            "type": "integer",
            "format": "int32"
          },
          "VehicleMake": {
            "type": "string"
          },
          "VehicleModel": {
            "type": "string"
          },
          "VehicleType": {
            "type": "string"
          },
          "VehicleYear": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "VehicleYear": 6,
          "VehicleDetailsId": 0,
          "VehicleModel": "VehicleModel",
          "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
          "id": "id",
          "VehicleMake": "VehicleMake",
          "VehicleType": "VehicleType"
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "addTypePrevious": {
            "type": "string"
          },
          "addTypePrimary": {
            "type": "string"
          },
          "annualIncome": {
            "type": "integer"
          },
          "anyPoliticalRelationship": {
            "type": "boolean"
          },
          "apartmentNo": {
            "type": "string"
          },
          "citizenOf": {
            "type": "boolean"
          },
          "\u30B7\u30C6\u30A3": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date-time"
          },
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "housingStatus": {
            "type": "string"
          },
          "initial": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "monthlyPayment": {
            "type": "integer"
          },
          "monthsAtCurrAdd": {
            "type": "integer",
            "format": "int32"
          },
          "otherIncome": {
            "type": "string"
          },
          "permanentResidence": {
            "type": "boolean"
          },
          "phoneNo": {
            "type": "integer",
            "format": "int32"
          },
          "ssn": {
            "type": "integer",
            "format": "int32"
          },
          "\u72B6\u614B": {
            "type": "string"
          },
          "\u901A\u308A\u72B6\u614B": {
            "type": "string"
          },
          "suffix": {
            "type": "string"
          },
          "uid": {
            "type": "integer",
            "format": "int32"
          },
          "userName": {
            "type": "string"
          },
          "yearsAtCurrAdd": {
            "type": "integer",
            "format": "int32"
          },
          "zipCode": {
            "type": "string"
          }
        },
        "example": {
          "apartmentNo": "apartmentNo",
          "lastName": "lastName",
          "zipCode": "zipCode",
          "annualIncome": 5,
          "housingStatus": "housingStatus",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "permanentResidence": true,
          "suffix": "suffix",
          "phoneNo": 1234,
          "ssn": 3,
          "uid": 2,
          "yearsAtCurrAdd": 4,
          "monthlyPayment": 2,
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "\u72B6\u614B": "\u72B6\u614B",
          "addTypePrimary": "addTypePrimary",
          "email": "email",
          "initial": "initial",
          "citizenOf": true,
          "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
          "userName": "userName",
          "otherIncome": "otherIncome",
          "firstName": "firstName",
          "addTypePrevious": "addTypePrevious",
          "anyPoliticalRelationship": true,
          "monthsAtCurrAdd": 7
        }
      },
      "Branch": {
        "type": "object",
        "properties": {
          "apartmentNo": {
            "type": "string"
          },
          "BranchId": {
            "type": "integer",
            "format": "int32"
          },
          "BranchName": {
            "type": "string"
          },
          "\u30B7\u30C6\u30A3": {
            "type": "string"
          },
          "contactPerson": {
            "type": "string"
          },
          "phoneNo": {
            "type": "string"
          },
          "\u72B6\u614B": {
            "type": "string"
          },
          "\u901A\u308A\u72B6\u614B": {
            "type": "string"
          },
          "zipCode": {
            "type": "string"
          }
        },
        "example": {
          "apartmentNo": "apartmentNo",
          "BranchId": 0,
          "zipCode": "zipCode",
          "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
          "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
          "BranchName": "BranchName",
          "contactPerson": "contactPerson",
          "\u72B6\u614B": "\u72B6\u614B",
          "phoneNo": "phoneNo"
        }
      },
      "Application": {
        "type": "object",
        "properties": {
          "ApplicationId": {
            "type": "string"
          },
          "Application\u72B6\u614B": {
            "type": "string"
          },
          "ApplicationStatus": {
            "type": "string"
          },
          "Branch": {
            "$ref": "#/components/schemas/Branch"
          },
          "loanTerm": {
            "type": "integer",
            "format": "int32"
          },
          "loanYearPeriod": {
            "type": "integer",
            "format": "int32"
          },
          "ownerShip": {
            "type": "string"
          },
          "pendingWith": {
            "type": "string"
          },
          "requestedAmt": {
            "type": "integer",
            "format": "int32"
          },
          "uid": {
            "type": "integer",
            "format": "int32"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "userName": {
            "type": "string"
          },
          "Vehicle": {
            "$ref": "#/components/schemas/Vehicle"
          }
        },
        "example": {
          "pendingWith": "pendingWith",
          "requestedAmt": 1,
          "Application\u72B6\u614B": "Application\u72B6\u614B",
          "ownerShip": "ownerShip",
          "userName": "userName",
          "Branch": {
            "apartmentNo": "apartmentNo",
            "BranchId": 0,
            "zipCode": "zipCode",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "BranchName": "BranchName",
            "contactPerson": "contactPerson",
            "\u72B6\u614B": "\u72B6\u614B",
            "phoneNo": "phoneNo"
          },
          "Vehicle": {
            "zipCode": "zipCode",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
            "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
            "VehicleMake": "VehicleMake",
            "transactionType": "transactionType",
            "\u63A8\u5B9A\u5024": 7,
            "VehicleYear": 1,
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
            "VehicleModel": "VehicleModel",
            "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
            "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
            "\u72B6\u614B": "\u72B6\u614B",
            "VehicleId": 1,
            "VehicleType": "VehicleType"
          },
          "loanYearPeriod": 6,
          "uid": 5,
          "loanTerm": 0,
          "ApplicationStatus": "ApplicationStatus",
          "ApplicationId": "ApplicationId",
          "user": {
            "apartmentNo": "apartmentNo",
            "lastName": "lastName",
            "zipCode": "zipCode",
            "annualIncome": 5,
            "housingStatus": "housingStatus",
            "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
            "permanentResidence": true,
            "suffix": "suffix",
            "phoneNo": 9,
            "ssn": 3,
            "uid": 2,
            "yearsAtCurrAdd": 4,
            "monthlyPayment": 2,
            "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
            "\u72B6\u614B": "\u72B6\u614B",
            "addTypePrimary": "addTypePrimary",
            "email": "email",
            "initial": "initial",
            "citizenOf": true,
            "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
            "userName": "userName",
            "otherIncome": "otherIncome",
            "firstName": "firstName",
            "addTypePrevious": "addTypePrevious",
            "anyPoliticalRelationship": true,
            "monthsAtCurrAdd": 7
          }
        }
      },
      "LoanApplication": {
        "type": "object",
        "properties": {
          "Application": {
            "$ref": "#/components/schemas/Application"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          }
        },
        "example": {
          "Application": {
            "pendingWith": "pendingWith",
            "requestedAmt": 1,
            "Application\u72B6\u614B": "Application\u72B6\u614B",
            "ownerShip": "ownerShip",
            "userName": "userName",
            "Branch": {
              "apartmentNo": "apartmentNo",
              "BranchId": 0,
              "zipCode": "zipCode",
              "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
              "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
              "BranchName": "BranchName",
              "contactPerson": "contactPerson",
              "\u72B6\u614B": "\u72B6\u614B",
              "phoneNo": "phoneNo"
            },
            "Vehicle": {
              "zipCode": "zipCode",
              "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
              "\u58F2\u308A\u624B\u540D": "\u58F2\u308A\u624B\u540D",
              "\u58F2\u308A\u624B\u4F4F\u6240": "\u58F2\u308A\u624B\u4F4F\u6240",
              "VehicleMake": "VehicleMake",
              "transactionType": "transactionType",
              "\u63A8\u5B9A\u5024": 7,
              "VehicleYear": 1,
              "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
              "\u7D04\u30DE\u30A4\u30EB": "\u7D04\u30DE\u30A4\u30EB",
              "VehicleModel": "VehicleModel",
              "\u30D3\u30FC\u30C7\u30F3": "\u30D3\u30FC\u30C7\u30F3",
              "\u767B\u9332\u5DDE": "\u767B\u9332\u5DDE",
              "\u72B6\u614B": "\u72B6\u614B",
              "VehicleId": 1,
              "VehicleType": "VehicleType"
            },
            "loanYearPeriod": 6,
            "uid": 5,
            "loanTerm": 0,
            "ApplicationStatus": "ApplicationStatus",
            "ApplicationId": "ApplicationId",
            "user": {
              "apartmentNo": "apartmentNo",
              "lastName": "lastName",
              "zipCode": "zipCode",
              "annualIncome": 5,
              "housingStatus": "housingStatus",
              "\u30B7\u30C6\u30A3": "\u30B7\u30C6\u30A3",
              "permanentResidence": true,
              "suffix": "suffix",
              "phoneNo": 9,
              "ssn": 3,
              "uid": 2,
              "yearsAtCurrAdd": 4,
              "monthlyPayment": 2,
              "\u901A\u308A\u72B6\u614B": "\u901A\u308A\u72B6\u614B",
              "\u72B6\u614B": "\u72B6\u614B",
              "addTypePrimary": "addTypePrimary",
              "email": "email",
              "initial": "initial",
              "citizenOf": true,
              "dateOfBirth": "2000-01-23T04:56:07.000+00:00",
              "userName": "userName",
              "otherIncome": "otherIncome",
              "firstName": "firstName",
              "addTypePrevious": "addTypePrevious",
              "anyPoliticalRelationship": true,
              "monthsAtCurrAdd": 7
            }
          }
        }
      }
    }
  }
}